language: "es-ES"

reviews:
  profile: "chill"
  high_level_summary: true
  poem: true

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - development
      - main

  path_instructions:
    - path: "**/openapi.yaml"
      instructions: |
        Revisa la guía de estilos "guia-estilos-api.md" que tenemos en la empresa y asegúrate de que el archivo "openapi.yaml" cumpla con todos los estándares de la guía.

        Indícame si hay algo que no se cumple y cómo se puede mejorar.

chat:
  auto_reply: true